import ClientProvider from '@/components/ClientProvider'
import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import './style.css'

const publicsans = Public_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Book the party',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={publicsans.className}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  )
}
