#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Clean the build folder
echo "Cleaning build folder..."
rm -rf .next build

# Run the build
echo "Building the project..."
if npm run build; then
  echo "Build succeeded! Proceeding with push..."
else
  echo "Build failed! Aborting push..."
  exit 1
fi
